#!/usr/bin/env python3
"""Regenerate flight_kml/airlines.py from the OpenFlights airlines dataset.

Download https://raw.githubusercontent.com/jpatokal/openflights/master/data/airlines.dat
into this directory, then run:

    python3 scripts/gen_airlines.py

The input path is fixed (scripts/airlines.dat, next to this script) — no
user-supplied paths are opened.

Entries marked active win on IATA-code conflicts; hand-curated overrides live
in flight_kml/ident.py (CURATED), not here.
"""
import csv
import pathlib
import sys


def build(path):
    table = {}
    with open(path, encoding="utf-8") as f:
        for row in csv.reader(f):
            if len(row) < 8:
                continue
            _, name, _, iata, icao, _, _country, active = row[:8]
            iata, icao = iata.strip().upper(), icao.strip().upper()
            if len(iata) != 2 or not iata.isalnum():
                continue
            if len(icao) != 3 or not icao.isalpha():
                continue
            active = active == "Y"
            if iata not in table or (active and not table[iata][1]):
                table[iata] = (icao, active)
    return {code: icao for code, (icao, _) in sorted(table.items())}


def main():
    if len(sys.argv) != 1:
        sys.exit(__doc__)
    src = pathlib.Path(__file__).resolve().parent / "airlines.dat"
    if not src.is_file():
        sys.exit(f"error: download airlines.dat into {src.parent} first")
    table = build(src)
    out = (pathlib.Path(__file__).resolve().parent.parent
           / "flight_kml" / "airlines.py")
    lines = [
        '"""IATA -> ICAO airline codes (%d entries).' % len(table),
        "",
        "Generated by scripts/gen_airlines.py from the OpenFlights airlines",
        "dataset. Do not edit by hand — put fixes in CURATED in ident.py.",
        '"""',
        "",
        "IATA_TO_ICAO = {",
    ]
    for code, icao in table.items():
        lines.append(f'    "{code}": "{icao}",')
    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out} with {len(table)} entries")


if __name__ == "__main__":
    main()
